%-----------------------------------------------------------------------
% Job saved on 06-May-2015 15:27:25 by cfg_util (rev $Rev: 6134 $)
% spm SPM - SPM12 (6225)
% cfg_basicio BasicIO - Unknown
%-----------------------------------------------------------------------
%%


matlabbatch{1}.spm.spatial.realign.estwrite.data = {
                                                    {
                                                    './nMR/verbs/verbs.nii,1'
                                                    './nMR/verbs/verbs.nii,2'
                                                    './nMR/verbs/verbs.nii,3'
                                                    './nMR/verbs/verbs.nii,4'
                                                    './nMR/verbs/verbs.nii,5'
                                                    './nMR/verbs/verbs.nii,6'
                                                    './nMR/verbs/verbs.nii,7'
                                                    './nMR/verbs/verbs.nii,8'
                                                    './nMR/verbs/verbs.nii,9'
                                                    './nMR/verbs/verbs.nii,10'
                                                    './nMR/verbs/verbs.nii,11'
                                                    './nMR/verbs/verbs.nii,12'
                                                    './nMR/verbs/verbs.nii,13'
                                                    './nMR/verbs/verbs.nii,14'
                                                    './nMR/verbs/verbs.nii,15'
                                                    './nMR/verbs/verbs.nii,16'
                                                    './nMR/verbs/verbs.nii,17'
                                                    './nMR/verbs/verbs.nii,18'
                                                    './nMR/verbs/verbs.nii,19'
                                                    './nMR/verbs/verbs.nii,20'
                                                    './nMR/verbs/verbs.nii,21'
                                                    './nMR/verbs/verbs.nii,22'
                                                    './nMR/verbs/verbs.nii,23'
                                                    './nMR/verbs/verbs.nii,24'
                                                    './nMR/verbs/verbs.nii,25'
                                                    './nMR/verbs/verbs.nii,26'
                                                    './nMR/verbs/verbs.nii,27'
                                                    './nMR/verbs/verbs.nii,28'
                                                    './nMR/verbs/verbs.nii,29'
                                                    './nMR/verbs/verbs.nii,30'
                                                    './nMR/verbs/verbs.nii,31'
                                                    './nMR/verbs/verbs.nii,32'
                                                    './nMR/verbs/verbs.nii,33'
                                                    './nMR/verbs/verbs.nii,34'
                                                    './nMR/verbs/verbs.nii,35'
                                                    './nMR/verbs/verbs.nii,36'
                                                    './nMR/verbs/verbs.nii,37'
                                                    './nMR/verbs/verbs.nii,38'
                                                    './nMR/verbs/verbs.nii,39'
                                                    './nMR/verbs/verbs.nii,40'
                                                    './nMR/verbs/verbs.nii,41'
                                                    './nMR/verbs/verbs.nii,42'
                                                    './nMR/verbs/verbs.nii,43'
                                                    './nMR/verbs/verbs.nii,44'
                                                    './nMR/verbs/verbs.nii,45'
                                                    './nMR/verbs/verbs.nii,46'
                                                    './nMR/verbs/verbs.nii,47'
                                                    './nMR/verbs/verbs.nii,48'
                                                    './nMR/verbs/verbs.nii,49'
                                                    './nMR/verbs/verbs.nii,50'
                                                    './nMR/verbs/verbs.nii,51'
                                                    './nMR/verbs/verbs.nii,52'
                                                    './nMR/verbs/verbs.nii,53'
                                                    './nMR/verbs/verbs.nii,54'
                                                    './nMR/verbs/verbs.nii,55'
                                                    './nMR/verbs/verbs.nii,56'
                                                    './nMR/verbs/verbs.nii,57'
                                                    './nMR/verbs/verbs.nii,58'
                                                    './nMR/verbs/verbs.nii,59'
                                                    './nMR/verbs/verbs.nii,60'
                                                    './nMR/verbs/verbs.nii,61'
                                                    './nMR/verbs/verbs.nii,62'
                                                    './nMR/verbs/verbs.nii,63'
                                                    './nMR/verbs/verbs.nii,64'
                                                    './nMR/verbs/verbs.nii,65'
                                                    './nMR/verbs/verbs.nii,66'
                                                    './nMR/verbs/verbs.nii,67'
                                                    './nMR/verbs/verbs.nii,68'
                                                    './nMR/verbs/verbs.nii,69'
                                                    './nMR/verbs/verbs.nii,70'
                                                    './nMR/verbs/verbs.nii,71'
                                                    './nMR/verbs/verbs.nii,72'
                                                    './nMR/verbs/verbs.nii,73'
                                                    './nMR/verbs/verbs.nii,74'
                                                    './nMR/verbs/verbs.nii,75'
                                                    './nMR/verbs/verbs.nii,76'
                                                    './nMR/verbs/verbs.nii,77'
                                                    './nMR/verbs/verbs.nii,78'
                                                    './nMR/verbs/verbs.nii,79'
                                                    './nMR/verbs/verbs.nii,80'
                                                    './nMR/verbs/verbs.nii,81'
                                                    './nMR/verbs/verbs.nii,82'
                                                    './nMR/verbs/verbs.nii,83'
                                                    './nMR/verbs/verbs.nii,84'
                                                    './nMR/verbs/verbs.nii,85'
                                                    './nMR/verbs/verbs.nii,86'
                                                    './nMR/verbs/verbs.nii,87'
                                                    './nMR/verbs/verbs.nii,88'
                                                    './nMR/verbs/verbs.nii,89'
                                                    './nMR/verbs/verbs.nii,90'
                                                    './nMR/verbs/verbs.nii,91'
                                                    './nMR/verbs/verbs.nii,92'
                                                    './nMR/verbs/verbs.nii,93'
                                                    './nMR/verbs/verbs.nii,94'
                                                    './nMR/verbs/verbs.nii,95'
                                                    './nMR/verbs/verbs.nii,96'
                                                    './nMR/verbs/verbs.nii,97'
                                                    './nMR/verbs/verbs.nii,98'
                                                    './nMR/verbs/verbs.nii,99'
                                                    './nMR/verbs/verbs.nii,100'
                                                    './nMR/verbs/verbs.nii,101'
                                                    './nMR/verbs/verbs.nii,102'
                                                    './nMR/verbs/verbs.nii,103'
                                                    './nMR/verbs/verbs.nii,104'
                                                    './nMR/verbs/verbs.nii,105'
                                                    './nMR/verbs/verbs.nii,106'
                                                    './nMR/verbs/verbs.nii,107'
                                                    './nMR/verbs/verbs.nii,108'
                                                    './nMR/verbs/verbs.nii,109'
                                                    './nMR/verbs/verbs.nii,110'
                                                    './nMR/verbs/verbs.nii,111'
                                                    './nMR/verbs/verbs.nii,112'
                                                    './nMR/verbs/verbs.nii,113'
                                                    './nMR/verbs/verbs.nii,114'
                                                    './nMR/verbs/verbs.nii,115'
                                                    './nMR/verbs/verbs.nii,116'
                                                    './nMR/verbs/verbs.nii,117'
                                                    './nMR/verbs/verbs.nii,118'
                                                    './nMR/verbs/verbs.nii,119'
                                                    './nMR/verbs/verbs.nii,120'
                                                    './nMR/verbs/verbs.nii,121'
                                                    './nMR/verbs/verbs.nii,122'
                                                    './nMR/verbs/verbs.nii,123'
                                                    './nMR/verbs/verbs.nii,124'
                                                    './nMR/verbs/verbs.nii,125'
                                                    './nMR/verbs/verbs.nii,126'
                                                    './nMR/verbs/verbs.nii,127'
                                                    './nMR/verbs/verbs.nii,128'
                                                    './nMR/verbs/verbs.nii,129'
                                                    './nMR/verbs/verbs.nii,130'
                                                    './nMR/verbs/verbs.nii,131'
                                                    './nMR/verbs/verbs.nii,132'
                                                    './nMR/verbs/verbs.nii,133'
                                                    './nMR/verbs/verbs.nii,134'
                                                    './nMR/verbs/verbs.nii,135'
                                                    './nMR/verbs/verbs.nii,136'
                                                    './nMR/verbs/verbs.nii,137'
                                                    './nMR/verbs/verbs.nii,138'
                                                    './nMR/verbs/verbs.nii,139'
                                                    './nMR/verbs/verbs.nii,140'
                                                    './nMR/verbs/verbs.nii,141'
                                                    './nMR/verbs/verbs.nii,142'
                                                    './nMR/verbs/verbs.nii,143'
                                                    './nMR/verbs/verbs.nii,144'
                                                    './nMR/verbs/verbs.nii,145'
                                                    './nMR/verbs/verbs.nii,146'
                                                    './nMR/verbs/verbs.nii,147'
                                                    './nMR/verbs/verbs.nii,148'
                                                    './nMR/verbs/verbs.nii,149'
                                                    './nMR/verbs/verbs.nii,150'
                                                    './nMR/verbs/verbs.nii,151'
                                                    './nMR/verbs/verbs.nii,152'
                                                    './nMR/verbs/verbs.nii,153'
                                                    './nMR/verbs/verbs.nii,154'
                                                    './nMR/verbs/verbs.nii,155'
                                                    './nMR/verbs/verbs.nii,156'
                                                    './nMR/verbs/verbs.nii,157'
                                                    './nMR/verbs/verbs.nii,158'
                                                    './nMR/verbs/verbs.nii,159'
                                                    './nMR/verbs/verbs.nii,160'
                                                    './nMR/verbs/verbs.nii,161'
                                                    './nMR/verbs/verbs.nii,162'
                                                    './nMR/verbs/verbs.nii,163'
                                                    './nMR/verbs/verbs.nii,164'
                                                    './nMR/verbs/verbs.nii,165'
                                                    './nMR/verbs/verbs.nii,166'
                                                    './nMR/verbs/verbs.nii,167'
                                                    './nMR/verbs/verbs.nii,168'
                                                    './nMR/verbs/verbs.nii,169'
                                                    './nMR/verbs/verbs.nii,170'
                                                    './nMR/verbs/verbs.nii,171'
                                                    './nMR/verbs/verbs.nii,172'
                                                    './nMR/verbs/verbs.nii,173'
                                                    './nMR/verbs/verbs.nii,174'
                                                    './nMR/verbs/verbs.nii,175'
                                                    './nMR/verbs/verbs.nii,176'
                                                    './nMR/verbs/verbs.nii,177'
                                                    './nMR/verbs/verbs.nii,178'
                                                    './nMR/verbs/verbs.nii,179'
                                                    './nMR/verbs/verbs.nii,180'
                                                    './nMR/verbs/verbs.nii,181'
                                                    './nMR/verbs/verbs.nii,182'
                                                    './nMR/verbs/verbs.nii,183'
                                                    './nMR/verbs/verbs.nii,184'
                                                    './nMR/verbs/verbs.nii,185'
                                                    './nMR/verbs/verbs.nii,186'
                                                    './nMR/verbs/verbs.nii,187'
                                                    './nMR/verbs/verbs.nii,188'
                                                    './nMR/verbs/verbs.nii,189'
                                                    './nMR/verbs/verbs.nii,190'
                                                    './nMR/verbs/verbs.nii,191'
                                                    './nMR/verbs/verbs.nii,192'
                                                    './nMR/verbs/verbs.nii,193'
                                                    './nMR/verbs/verbs.nii,194'
                                                    './nMR/verbs/verbs.nii,195'
                                                    './nMR/verbs/verbs.nii,196'
                                                    './nMR/verbs/verbs.nii,197'
                                                    './nMR/verbs/verbs.nii,198'
                                                    './nMR/verbs/verbs.nii,199'
                                                    './nMR/verbs/verbs.nii,200'
                                                    './nMR/verbs/verbs.nii,201'
                                                    './nMR/verbs/verbs.nii,202'
                                                    './nMR/verbs/verbs.nii,203'
                                                    './nMR/verbs/verbs.nii,204'
                                                    './nMR/verbs/verbs.nii,205'
                                                    './nMR/verbs/verbs.nii,206'
                                                    './nMR/verbs/verbs.nii,207'
                                                    './nMR/verbs/verbs.nii,208'
                                                    './nMR/verbs/verbs.nii,209'
                                                    './nMR/verbs/verbs.nii,210'
                                                    './nMR/verbs/verbs.nii,211'
                                                    }
                                                    }';
%%
matlabbatch{1}.spm.spatial.realign.estwrite.eoptions.quality = 0.9;
matlabbatch{1}.spm.spatial.realign.estwrite.eoptions.sep = 4;
matlabbatch{1}.spm.spatial.realign.estwrite.eoptions.fwhm = 5;
matlabbatch{1}.spm.spatial.realign.estwrite.eoptions.rtm = 1;
matlabbatch{1}.spm.spatial.realign.estwrite.eoptions.interp = 2;
matlabbatch{1}.spm.spatial.realign.estwrite.eoptions.wrap = [0 0 0];
matlabbatch{1}.spm.spatial.realign.estwrite.eoptions.weight = '';
matlabbatch{1}.spm.spatial.realign.estwrite.roptions.which = [0 1];
matlabbatch{1}.spm.spatial.realign.estwrite.roptions.interp = 4;
matlabbatch{1}.spm.spatial.realign.estwrite.roptions.wrap = [0 0 0];
matlabbatch{1}.spm.spatial.realign.estwrite.roptions.mask = 1;
matlabbatch{1}.spm.spatial.realign.estwrite.roptions.prefix = 'r';
matlabbatch{2}.spm.spatial.coreg.estimate.ref(1) = cfg_dep('Realign: Estimate & Reslice: Mean Image', substruct('.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','rmean'));
matlabbatch{2}.spm.spatial.coreg.estimate.source = {'./nMR/T1/T1.nii,1'};
matlabbatch{2}.spm.spatial.coreg.estimate.other = {''};
matlabbatch{2}.spm.spatial.coreg.estimate.eoptions.cost_fun = 'nmi';
matlabbatch{2}.spm.spatial.coreg.estimate.eoptions.sep = [4 2];
matlabbatch{2}.spm.spatial.coreg.estimate.eoptions.tol = [0.02 0.02 0.02 0.001 0.001 0.001 0.01 0.01 0.01 0.001 0.001 0.001];
matlabbatch{2}.spm.spatial.coreg.estimate.eoptions.fwhm = [7 7];
matlabbatch{3}.spm.spatial.preproc.channel.vols(1) = cfg_dep('Coregister: Estimate: Coregistered Images', substruct('.','val', '{}',{2}, '.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','cfiles'));
matlabbatch{3}.spm.spatial.preproc.channel.biasreg = 0.001;
matlabbatch{3}.spm.spatial.preproc.channel.biasfwhm = 60;
matlabbatch{3}.spm.spatial.preproc.channel.write = [0 0];
matlabbatch{3}.spm.spatial.preproc.tissue(1).tpm = {'/Users/toryz8/Documents/MATLAB/spm12/tpm/TPM.nii,1'};
matlabbatch{3}.spm.spatial.preproc.tissue(1).ngaus = 1;
matlabbatch{3}.spm.spatial.preproc.tissue(1).native = [1 0];
matlabbatch{3}.spm.spatial.preproc.tissue(1).warped = [0 0];
matlabbatch{3}.spm.spatial.preproc.tissue(2).tpm = {'/Users/toryz8/Documents/MATLAB/spm12/tpm/TPM.nii,2'};
matlabbatch{3}.spm.spatial.preproc.tissue(2).ngaus = 1;
matlabbatch{3}.spm.spatial.preproc.tissue(2).native = [1 0];
matlabbatch{3}.spm.spatial.preproc.tissue(2).warped = [0 0];
matlabbatch{3}.spm.spatial.preproc.tissue(3).tpm = {'/Users/toryz8/Documents/MATLAB/spm12/tpm/TPM.nii,3'};
matlabbatch{3}.spm.spatial.preproc.tissue(3).ngaus = 2;
matlabbatch{3}.spm.spatial.preproc.tissue(3).native = [1 0];
matlabbatch{3}.spm.spatial.preproc.tissue(3).warped = [0 0];
matlabbatch{3}.spm.spatial.preproc.tissue(4).tpm = {'/Users/toryz8/Documents/MATLAB/spm12/tpm/TPM.nii,4'};
matlabbatch{3}.spm.spatial.preproc.tissue(4).ngaus = 3;
matlabbatch{3}.spm.spatial.preproc.tissue(4).native = [1 0];
matlabbatch{3}.spm.spatial.preproc.tissue(4).warped = [0 0];
matlabbatch{3}.spm.spatial.preproc.tissue(5).tpm = {'/Users/toryz8/Documents/MATLAB/spm12/tpm/TPM.nii,5'};
matlabbatch{3}.spm.spatial.preproc.tissue(5).ngaus = 4;
matlabbatch{3}.spm.spatial.preproc.tissue(5).native = [1 0];
matlabbatch{3}.spm.spatial.preproc.tissue(5).warped = [0 0];
matlabbatch{3}.spm.spatial.preproc.tissue(6).tpm = {'/Users/toryz8/Documents/MATLAB/spm12/tpm/TPM.nii,6'};
matlabbatch{3}.spm.spatial.preproc.tissue(6).ngaus = 2;
matlabbatch{3}.spm.spatial.preproc.tissue(6).native = [0 0];
matlabbatch{3}.spm.spatial.preproc.tissue(6).warped = [0 0];
matlabbatch{3}.spm.spatial.preproc.warp.mrf = 1;
matlabbatch{3}.spm.spatial.preproc.warp.cleanup = 1;
matlabbatch{3}.spm.spatial.preproc.warp.reg = [0 0.001 0.5 0.05 0.2];
matlabbatch{3}.spm.spatial.preproc.warp.affreg = 'mni';
matlabbatch{3}.spm.spatial.preproc.warp.fwhm = 0;
matlabbatch{3}.spm.spatial.preproc.warp.samp = 3;
matlabbatch{3}.spm.spatial.preproc.warp.write = [0 1];
matlabbatch{4}.spm.spatial.normalise.write.subj.def(1) = cfg_dep('Segment: Forward Deformations', substruct('.','val', '{}',{3}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','fordef', '()',{':'}));
%%
matlabbatch{4}.spm.spatial.normalise.write.subj.resample = {
                                                            './nMR/verbs/verbs.nii,1'
                                                            './nMR/verbs/verbs.nii,2'
                                                            './nMR/verbs/verbs.nii,3'
                                                            './nMR/verbs/verbs.nii,4'
                                                            './nMR/verbs/verbs.nii,5'
                                                            './nMR/verbs/verbs.nii,6'
                                                            './nMR/verbs/verbs.nii,7'
                                                            './nMR/verbs/verbs.nii,8'
                                                            './nMR/verbs/verbs.nii,9'
                                                            './nMR/verbs/verbs.nii,10'
                                                            './nMR/verbs/verbs.nii,11'
                                                            './nMR/verbs/verbs.nii,12'
                                                            './nMR/verbs/verbs.nii,13'
                                                            './nMR/verbs/verbs.nii,14'
                                                            './nMR/verbs/verbs.nii,15'
                                                            './nMR/verbs/verbs.nii,16'
                                                            './nMR/verbs/verbs.nii,17'
                                                            './nMR/verbs/verbs.nii,18'
                                                            './nMR/verbs/verbs.nii,19'
                                                            './nMR/verbs/verbs.nii,20'
                                                            './nMR/verbs/verbs.nii,21'
                                                            './nMR/verbs/verbs.nii,22'
                                                            './nMR/verbs/verbs.nii,23'
                                                            './nMR/verbs/verbs.nii,24'
                                                            './nMR/verbs/verbs.nii,25'
                                                            './nMR/verbs/verbs.nii,26'
                                                            './nMR/verbs/verbs.nii,27'
                                                            './nMR/verbs/verbs.nii,28'
                                                            './nMR/verbs/verbs.nii,29'
                                                            './nMR/verbs/verbs.nii,30'
                                                            './nMR/verbs/verbs.nii,31'
                                                            './nMR/verbs/verbs.nii,32'
                                                            './nMR/verbs/verbs.nii,33'
                                                            './nMR/verbs/verbs.nii,34'
                                                            './nMR/verbs/verbs.nii,35'
                                                            './nMR/verbs/verbs.nii,36'
                                                            './nMR/verbs/verbs.nii,37'
                                                            './nMR/verbs/verbs.nii,38'
                                                            './nMR/verbs/verbs.nii,39'
                                                            './nMR/verbs/verbs.nii,40'
                                                            './nMR/verbs/verbs.nii,41'
                                                            './nMR/verbs/verbs.nii,42'
                                                            './nMR/verbs/verbs.nii,43'
                                                            './nMR/verbs/verbs.nii,44'
                                                            './nMR/verbs/verbs.nii,45'
                                                            './nMR/verbs/verbs.nii,46'
                                                            './nMR/verbs/verbs.nii,47'
                                                            './nMR/verbs/verbs.nii,48'
                                                            './nMR/verbs/verbs.nii,49'
                                                            './nMR/verbs/verbs.nii,50'
                                                            './nMR/verbs/verbs.nii,51'
                                                            './nMR/verbs/verbs.nii,52'
                                                            './nMR/verbs/verbs.nii,53'
                                                            './nMR/verbs/verbs.nii,54'
                                                            './nMR/verbs/verbs.nii,55'
                                                            './nMR/verbs/verbs.nii,56'
                                                            './nMR/verbs/verbs.nii,57'
                                                            './nMR/verbs/verbs.nii,58'
                                                            './nMR/verbs/verbs.nii,59'
                                                            './nMR/verbs/verbs.nii,60'
                                                            './nMR/verbs/verbs.nii,61'
                                                            './nMR/verbs/verbs.nii,62'
                                                            './nMR/verbs/verbs.nii,63'
                                                            './nMR/verbs/verbs.nii,64'
                                                            './nMR/verbs/verbs.nii,65'
                                                            './nMR/verbs/verbs.nii,66'
                                                            './nMR/verbs/verbs.nii,67'
                                                            './nMR/verbs/verbs.nii,68'
                                                            './nMR/verbs/verbs.nii,69'
                                                            './nMR/verbs/verbs.nii,70'
                                                            './nMR/verbs/verbs.nii,71'
                                                            './nMR/verbs/verbs.nii,72'
                                                            './nMR/verbs/verbs.nii,73'
                                                            './nMR/verbs/verbs.nii,74'
                                                            './nMR/verbs/verbs.nii,75'
                                                            './nMR/verbs/verbs.nii,76'
                                                            './nMR/verbs/verbs.nii,77'
                                                            './nMR/verbs/verbs.nii,78'
                                                            './nMR/verbs/verbs.nii,79'
                                                            './nMR/verbs/verbs.nii,80'
                                                            './nMR/verbs/verbs.nii,81'
                                                            './nMR/verbs/verbs.nii,82'
                                                            './nMR/verbs/verbs.nii,83'
                                                            './nMR/verbs/verbs.nii,84'
                                                            './nMR/verbs/verbs.nii,85'
                                                            './nMR/verbs/verbs.nii,86'
                                                            './nMR/verbs/verbs.nii,87'
                                                            './nMR/verbs/verbs.nii,88'
                                                            './nMR/verbs/verbs.nii,89'
                                                            './nMR/verbs/verbs.nii,90'
                                                            './nMR/verbs/verbs.nii,91'
                                                            './nMR/verbs/verbs.nii,92'
                                                            './nMR/verbs/verbs.nii,93'
                                                            './nMR/verbs/verbs.nii,94'
                                                            './nMR/verbs/verbs.nii,95'
                                                            './nMR/verbs/verbs.nii,96'
                                                            './nMR/verbs/verbs.nii,97'
                                                            './nMR/verbs/verbs.nii,98'
                                                            './nMR/verbs/verbs.nii,99'
                                                            './nMR/verbs/verbs.nii,100'
                                                            './nMR/verbs/verbs.nii,101'
                                                            './nMR/verbs/verbs.nii,102'
                                                            './nMR/verbs/verbs.nii,103'
                                                            './nMR/verbs/verbs.nii,104'
                                                            './nMR/verbs/verbs.nii,105'
                                                            './nMR/verbs/verbs.nii,106'
                                                            './nMR/verbs/verbs.nii,107'
                                                            './nMR/verbs/verbs.nii,108'
                                                            './nMR/verbs/verbs.nii,109'
                                                            './nMR/verbs/verbs.nii,110'
                                                            './nMR/verbs/verbs.nii,111'
                                                            './nMR/verbs/verbs.nii,112'
                                                            './nMR/verbs/verbs.nii,113'
                                                            './nMR/verbs/verbs.nii,114'
                                                            './nMR/verbs/verbs.nii,115'
                                                            './nMR/verbs/verbs.nii,116'
                                                            './nMR/verbs/verbs.nii,117'
                                                            './nMR/verbs/verbs.nii,118'
                                                            './nMR/verbs/verbs.nii,119'
                                                            './nMR/verbs/verbs.nii,120'
                                                            './nMR/verbs/verbs.nii,121'
                                                            './nMR/verbs/verbs.nii,122'
                                                            './nMR/verbs/verbs.nii,123'
                                                            './nMR/verbs/verbs.nii,124'
                                                            './nMR/verbs/verbs.nii,125'
                                                            './nMR/verbs/verbs.nii,126'
                                                            './nMR/verbs/verbs.nii,127'
                                                            './nMR/verbs/verbs.nii,128'
                                                            './nMR/verbs/verbs.nii,129'
                                                            './nMR/verbs/verbs.nii,130'
                                                            './nMR/verbs/verbs.nii,131'
                                                            './nMR/verbs/verbs.nii,132'
                                                            './nMR/verbs/verbs.nii,133'
                                                            './nMR/verbs/verbs.nii,134'
                                                            './nMR/verbs/verbs.nii,135'
                                                            './nMR/verbs/verbs.nii,136'
                                                            './nMR/verbs/verbs.nii,137'
                                                            './nMR/verbs/verbs.nii,138'
                                                            './nMR/verbs/verbs.nii,139'
                                                            './nMR/verbs/verbs.nii,140'
                                                            './nMR/verbs/verbs.nii,141'
                                                            './nMR/verbs/verbs.nii,142'
                                                            './nMR/verbs/verbs.nii,143'
                                                            './nMR/verbs/verbs.nii,144'
                                                            './nMR/verbs/verbs.nii,145'
                                                            './nMR/verbs/verbs.nii,146'
                                                            './nMR/verbs/verbs.nii,147'
                                                            './nMR/verbs/verbs.nii,148'
                                                            './nMR/verbs/verbs.nii,149'
                                                            './nMR/verbs/verbs.nii,150'
                                                            './nMR/verbs/verbs.nii,151'
                                                            './nMR/verbs/verbs.nii,152'
                                                            './nMR/verbs/verbs.nii,153'
                                                            './nMR/verbs/verbs.nii,154'
                                                            './nMR/verbs/verbs.nii,155'
                                                            './nMR/verbs/verbs.nii,156'
                                                            './nMR/verbs/verbs.nii,157'
                                                            './nMR/verbs/verbs.nii,158'
                                                            './nMR/verbs/verbs.nii,159'
                                                            './nMR/verbs/verbs.nii,160'
                                                            './nMR/verbs/verbs.nii,161'
                                                            './nMR/verbs/verbs.nii,162'
                                                            './nMR/verbs/verbs.nii,163'
                                                            './nMR/verbs/verbs.nii,164'
                                                            './nMR/verbs/verbs.nii,165'
                                                            './nMR/verbs/verbs.nii,166'
                                                            './nMR/verbs/verbs.nii,167'
                                                            './nMR/verbs/verbs.nii,168'
                                                            './nMR/verbs/verbs.nii,169'
                                                            './nMR/verbs/verbs.nii,170'
                                                            './nMR/verbs/verbs.nii,171'
                                                            './nMR/verbs/verbs.nii,172'
                                                            './nMR/verbs/verbs.nii,173'
                                                            './nMR/verbs/verbs.nii,174'
                                                            './nMR/verbs/verbs.nii,175'
                                                            './nMR/verbs/verbs.nii,176'
                                                            './nMR/verbs/verbs.nii,177'
                                                            './nMR/verbs/verbs.nii,178'
                                                            './nMR/verbs/verbs.nii,179'
                                                            './nMR/verbs/verbs.nii,180'
                                                            './nMR/verbs/verbs.nii,181'
                                                            './nMR/verbs/verbs.nii,182'
                                                            './nMR/verbs/verbs.nii,183'
                                                            './nMR/verbs/verbs.nii,184'
                                                            './nMR/verbs/verbs.nii,185'
                                                            './nMR/verbs/verbs.nii,186'
                                                            './nMR/verbs/verbs.nii,187'
                                                            './nMR/verbs/verbs.nii,188'
                                                            './nMR/verbs/verbs.nii,189'
                                                            './nMR/verbs/verbs.nii,190'
                                                            './nMR/verbs/verbs.nii,191'
                                                            './nMR/verbs/verbs.nii,192'
                                                            './nMR/verbs/verbs.nii,193'
                                                            './nMR/verbs/verbs.nii,194'
                                                            './nMR/verbs/verbs.nii,195'
                                                            './nMR/verbs/verbs.nii,196'
                                                            './nMR/verbs/verbs.nii,197'
                                                            './nMR/verbs/verbs.nii,198'
                                                            './nMR/verbs/verbs.nii,199'
                                                            './nMR/verbs/verbs.nii,200'
                                                            './nMR/verbs/verbs.nii,201'
                                                            './nMR/verbs/verbs.nii,202'
                                                            './nMR/verbs/verbs.nii,203'
                                                            './nMR/verbs/verbs.nii,204'
                                                            './nMR/verbs/verbs.nii,205'
                                                            './nMR/verbs/verbs.nii,206'
                                                            './nMR/verbs/verbs.nii,207'
                                                            './nMR/verbs/verbs.nii,208'
                                                            './nMR/verbs/verbs.nii,209'
                                                            './nMR/verbs/verbs.nii,210'
                                                            './nMR/verbs/verbs.nii,211'
                                                            };
%%
matlabbatch{4}.spm.spatial.normalise.write.woptions.bb = [-78 -112 -70
                                                          78 76 85];
matlabbatch{4}.spm.spatial.normalise.write.woptions.vox = [2 2 2];
matlabbatch{4}.spm.spatial.normalise.write.woptions.interp = 4;
matlabbatch{5}.spm.spatial.smooth.data(1) = cfg_dep('Normalise: Write: Normalised Images (Subj 1)', substruct('.','val', '{}',{4}, '.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('()',{1}, '.','files'));
matlabbatch{5}.spm.spatial.smooth.fwhm = [8 8 8];
matlabbatch{5}.spm.spatial.smooth.dtype = 0;
matlabbatch{5}.spm.spatial.smooth.im = 0;
matlabbatch{5}.spm.spatial.smooth.prefix = 's';
